name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: repo contents
      run: |
        ls -l
        docker --version
    - name: checking if java and maven installed or not
      run: |
        java -version
        mvn -version
        
