name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: repo contents
      run: |
        ls -l
        docker --version
        
    - name: getting all dependencies
      run: |
        mvn clean install
    - name: copying jar files in to docker repo
      run: |
        cp target/*.war src/main/docker/
        
    - name: Building the image
      run: |
        cd src/main/docker
        docker build -t tomcat:1 .
        ipconfig
    - name: Deploying application
      run: |
        docker container run -p 8080:8080 tomcat:1
        
