name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: repo contents
      run: |
        ls -l
        docker --version
        
    - name: getting all dependencies
      run: |
        mvn clean install
        sudo apt install curl
    - name: copying jar files in to docker repo
      run: |
        cp target/*.war src/main/docker/
        
    - name: Building the image
      run: |
        cd src/main/docker
        docker build -t tomcat:1 .
    - uses: anchore/scan-action@master
      with:
        image-reference: "localbuild/tomcat:1"
        dockerfile-path: "./Dockerfile"
        fail-build: true
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
        
